### ISSUE TITLE
Finish glossary page

### ISSUE THREAD

**Issue by fahimshekaib** [fahimshekaib/github-for-web-designers#1]
Fahim, can you please finish the glossary.html page? It needs terms and definitions.
Thanks!

**Comment by ahmadayub** [comment]
Yep, I'll get working on this tonight.

**Comment by fahimshekaib** [comment]
Thanks Fahim, I appreciate the hard work!

**Comment by ahmadayub** [comment]
Sorry to reopen this, I'll be able to do some of it tonight, but I won't be done till Friday.

**Comment by fahimshekaib** [comment]
That's okay, thanks again.
